# Generated by Django 6.0.2 on 2026-03-08 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
